export const THEMES = {
    vogue: {
        id: 'vogue',
        pageBg: 'bg-white',
        text: 'text-black',
        textMuted: 'text-gray-500',
        header: 'bg-white border-b border-gray-200',
        headerWrapper: 'max-w-[1440px] mx-auto px-4 sm:px-6 lg:px-8 h-24 grid grid-cols-3 items-center',
        logoWrapper: 'justify-self-center col-start-2 flex flex-row items-center',
        searchWrapper: 'hidden md:flex justify-self-start col-start-1 w-full max-w-xs',
        cartWrapper: 'justify-self-end col-start-3',
        headerLogo: 'hidden',
        heroShape: 'rounded-none',
        heroOverlay: 'bg-black/5',
        gridCols: 'grid-cols-1 sm:grid-cols-2 lg:grid-cols-2 gap-x-12 gap-y-16', // 2 columns for gallery look
        cardStyle: 'bg-white border border-gray-100 rounded-2xl shadow-sm hover:shadow-lg hover:border-gray-200 transition-all duration-300 overflow-hidden',
        cardImageStyle: 'aspect-square rounded-t-2xl bg-gray-50 border-b border-gray-100',
        badgeStyle: 'bg-black text-white rounded-full px-2.5 py-1 text-[10px] font-semibold uppercase tracking-wider',
        priceStyle: 'text-black font-medium text-lg',
        priceCompareStyle: 'text-gray-400 line-through text-sm',
        buttonStyle: 'w-full py-3 bg-white text-black border border-black hover:bg-black hover:text-white uppercase tracking-widest text-xs transition-colors rounded-[15px]',
        categoryTab: 'bg-transparent text-gray-500 border-b-2 border-transparent hover:text-black',
        categoryTabActive: 'bg-transparent text-black border-b-2 border-black font-semibold',
        searchStyle: 'bg-gray-50 border-none rounded-none focus:ring-1 focus:ring-black',
        fontFamily: "'Outfit', sans-serif",
        cartButton: 'bg-black text-white rounded-none hover:bg-gray-900',
        cartBadge: 'bg-white text-black',
    },
    cyber: {
        id: 'cyber',
        pageBg: 'bg-slate-950',
        text: 'text-white',
        textMuted: 'text-white/80',
        header: 'bg-slate-950/80 backdrop-blur-xl border-b border-slate-800 sticky top-0 z-50',
        headerWrapper: 'max-w-[1440px] mx-auto px-4 sm:px-6 lg:px-8 h-20 flex items-center justify-between',
        headerLogo: 'text-blue-500 font-bold tracking-tight',
        heroShape: 'rounded-none border-b border-slate-800',
        heroOverlay: 'bg-gradient-to-t from-slate-950 via-slate-950/40 to-transparent',
        gridCols: 'grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6',
        cardStyle: 'bg-slate-900 border border-slate-800 rounded-2xl hover:border-blue-500/50 hover:shadow-lg hover:shadow-blue-500/10 transition-all duration-300 overflow-hidden group',
        cardImageStyle: 'aspect-square bg-white p-4', // bg-white fixes the mix-blend-multiply issue for dark themes
        badgeStyle: 'bg-blue-600 text-white rounded-full px-3 py-1 text-xs font-bold shadow-md shadow-blue-900/20',
        priceStyle: 'text-blue-400 font-bold text-lg',
        priceCompareStyle: 'text-slate-500 line-through font-medium text-sm',
        buttonStyle: 'w-full py-3.5 bg-blue-600 text-white hover:bg-blue-500 rounded-xl font-bold transition-all shadow-md shadow-blue-900/20',
        categoryTab: 'bg-slate-900 text-slate-300 border border-slate-800 rounded-full font-medium hover:border-slate-600 hover:text-white transition-colors',
        categoryTabActive: 'bg-blue-600 text-white border border-blue-500 rounded-full font-bold shadow-md shadow-blue-900/30',
        categoryImageShape: 'rounded-2xl',
        searchStyle: 'bg-slate-900 border border-slate-800 text-slate-100 rounded-xl focus:border-blue-500 focus:ring-1 focus:ring-blue-500 placeholder-slate-500 transition-colors',
        headerSearch: 'bg-slate-900/50 border border-white/80 hover:border-white focus:border-white text-white placeholder-slate-400',
        fontFamily: "'Inter', system-ui, sans-serif",
        cartButton: 'bg-slate-800/80 text-white border border-slate-700 rounded-xl hover:bg-slate-700 hover:text-blue-300 transition-colors shadow-md',
        cartBadge: 'bg-blue-500 text-white rounded-full',
    },
    glow: {
        id: 'glow',
        pageBg: 'bg-rose-50/50',
        mobileNavBg: 'bg-rose-50',
        text: 'text-stone-700',
        textMuted: 'text-stone-500',
        header: 'bg-white/70 backdrop-blur-xl border-b border-rose-100',
        headerWrapper: 'max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 h-20 flex items-center justify-between', // Centered max-w
        headerLogo: 'text-rose-600',
        heroShape: 'rounded-none', // Removed huge bottom curve for full width
        heroOverlay: 'bg-rose-900/5',
        gridCols: 'grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8',
        cardStyle: 'bg-white/60 backdrop-blur-lg border border-white rounded-3xl shadow-sm hover:shadow-xl hover:shadow-rose-100/50 transition-all duration-500',
        cardImageStyle: 'aspect-[3/4] rounded-t-3xl bg-rose-50/50 p-2',
        badgeStyle: 'bg-gradient-to-r from-rose-400 to-pink-400 text-white rounded-full px-3 py-1 text-[10px]',
        priceStyle: 'text-rose-900 font-semibold text-lg',
        priceCompareStyle: 'text-rose-300 line-through text-sm',
        buttonStyle: 'w-full py-3 bg-gradient-to-r from-rose-400 to-pink-500 text-white hover:from-rose-500 hover:to-pink-600 rounded-2xl shadow-md shadow-rose-200 transition-all font-medium',
        categoryTab: 'bg-white/60 text-rose-400 rounded-full hover:bg-rose-100/50 hover:text-rose-600',
        categoryTabActive: 'bg-rose-100 text-rose-700 rounded-full font-medium shadow-sm',
        searchStyle: 'bg-white/60 border border-white text-rose-900 rounded-full focus:ring-2 focus:ring-rose-200 placeholder-rose-300 shadow-inner',
        fontFamily: "'Outfit', sans-serif",
        cartButton: 'bg-rose-100 text-rose-600 rounded-full hover:bg-rose-200',
        cartBadge: 'bg-gradient-to-r from-rose-400 to-pink-500 text-white',
    },
    jewelry: {
        id: 'jewelry',
        pageBg: 'bg-[#FCF9F9]',
        mobileNavBg: 'bg-[#EAD8DB]',
        text: 'text-[#261C1D]',
        textMuted: 'text-[#91777A]',
        header: 'bg-[#EAD8DB]/95 backdrop-blur-md border-b border-[#B76E79]/35 shadow-xs sticky top-0 z-50',
        headerWrapper: 'max-w-[1440px] mx-auto px-4 sm:px-6 lg:px-8 h-16 sm:h-20 flex items-center justify-between',
        headerLogo: 'text-[#261C1D] uppercase tracking-[0.25em] text-sm font-medium',
        headerSearch: 'bg-white/80 border border-[#D5B8BD] text-[#261C1D] placeholder-[#91777A] focus:bg-white focus:border-[#B76E79]',
        heroShape: 'rounded-none',
        heroOverlay: 'bg-gradient-to-t from-[#261C1D]/55 via-[#261C1D]/10 to-transparent',
        gridCols: 'grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-3 sm:gap-5',
        cardStyle: 'bg-white border border-[#EEDCDC] hover:border-[#B76E79] hover:shadow-[0_6px_24px_rgba(183,110,121,0.15)] transition-all duration-500 rounded-none group overflow-hidden',
        cardImageStyle: 'aspect-[4/5] bg-[#F8F2F2] group-hover:brightness-105 transition-all duration-700 rounded-none',
        badgeStyle: 'bg-[#B76E79] text-white rounded-none px-2 py-0.5 text-[9px] font-bold uppercase tracking-[0.15em]',
        priceStyle: 'text-[#A85D6A] font-semibold tracking-wide text-sm',
        priceCompareStyle: 'text-[#C2A7AA] line-through text-xs',
        buttonStyle: 'w-full py-2.5 bg-[#261C1D] text-[#FCF9F9] border border-[#261C1D] hover:bg-[#B76E79] hover:border-[#B76E79] hover:text-white uppercase tracking-[0.18em] text-[10px] font-semibold transition-all duration-300 rounded-none',
        categoryTab: 'bg-transparent text-[#91777A] border-b border-transparent rounded-none uppercase tracking-[0.12em] text-[10px] hover:text-[#A85D6A] hover:border-[#B76E79]/50 transition-all duration-200',
        categoryTabActive: 'bg-transparent text-[#A85D6A] border-b-2 border-[#B76E79] rounded-none uppercase tracking-[0.12em] text-[10px] font-semibold',
        searchStyle: 'bg-white border border-[#EEDCDC] text-[#261C1D] rounded-none focus:border-[#B76E79] focus:ring-0 placeholder-[#C2A7AA] text-sm px-3 py-1.5 transition-colors duration-200',
        fontFamily: "'Outfit', 'Inter', sans-serif",
        cartButton: 'text-[#91777A] hover:text-[#261C1D] hover:bg-black/5 transition-colors',
        cartBadge: 'bg-[#B76E79] text-white rounded-full font-bold text-[10px]',
        bgPatternStyle: {
            backgroundImage: [
                "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='60' height='60'%3E%3Cpath d='M30 0 L60 30 L30 60 L0 30 Z' fill='none' stroke='%23B76E79' stroke-width='0.8' opacity='0.12'%2F%3E%3C%2Fsvg%3E\")",
                "radial-gradient(ellipse 60% 45% at 92% 4%, rgba(183,110,121,0.09) 0%, transparent 70%)",
                "radial-gradient(ellipse 50% 40% at 8% 96%, rgba(183,110,121,0.07) 0%, transparent 70%)",
                "radial-gradient(ellipse 40% 30% at 50% 50%, rgba(183,110,121,0.03) 0%, transparent 80%)",
            ].join(', '),
            backgroundSize: '60px 60px, 100% 100%, 100% 100%, 100% 100%',
            backgroundRepeat: 'repeat, no-repeat, no-repeat, no-repeat',
            fontSize: '14.5px',
        },
        sparkleEffect: true,
    },

    crave: {
        id: 'crave',
        pageBg: 'bg-[#F6FBF7]',
        text: 'text-slate-900',
        textMuted: 'text-emerald-800/60',
        header: 'bg-[#F6FBF7]/90 backdrop-blur-sm border-b border-emerald-200/50',
        headerWrapper: 'max-w-[1440px] mx-auto px-4 sm:px-6 lg:px-8 h-20 flex items-center justify-between',
        heroShape: 'rounded-none', // Removed rounded borders for full width
        heroOverlay: 'bg-emerald-950/10',
        gridCols: 'grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6',
        cardStyle: 'bg-white border-2 border-transparent hover:border-emerald-200 rounded-3xl shadow-sm hover:shadow-xl hover:shadow-emerald-200/40 transition-all duration-300 overflow-hidden',
        cardImageStyle: 'aspect-square rounded-t-3xl bg-white',
        badgeStyle: 'bg-emerald-600 text-white rounded-full font-bold px-3 py-1',
        priceStyle: 'text-emerald-700 font-black text-xl',
        priceCompareStyle: 'text-emerald-300 line-through font-medium text-sm',
        buttonStyle: 'w-full py-3.5 bg-emerald-600 text-white hover:bg-emerald-700 rounded-2xl shadow-[0_4px_0_rgb(4,120,87)] active:shadow-[0_0px_0_rgb(4,120,87)] active:translate-y-1 font-bold text-base transition-all',
        categoryTab: 'bg-white text-emerald-700 rounded-full font-bold hover:bg-emerald-50 hover:text-emerald-800 shadow-sm border border-emerald-100',
        categoryTabActive: 'bg-emerald-600 text-white rounded-full font-bold shadow-md shadow-emerald-600/30',
        searchStyle: 'bg-white border border-emerald-200 text-slate-900 rounded-2xl focus:border-emerald-500 focus:ring-4 focus:ring-emerald-100 placeholder-emerald-400/60 font-medium',
        headerSearch: 'bg-white border border-emerald-200 text-slate-900 placeholder-emerald-400/60 focus:border-emerald-500 focus:ring-2 focus:ring-emerald-100',
        fontFamily: "'Nunito', sans-serif",
        cartButton: 'bg-white text-emerald-700 rounded-2xl border border-emerald-200 hover:bg-emerald-50 hover:border-emerald-300 shadow-sm',
        cartBadge: 'bg-emerald-600 text-white',
    },
    fresh: {
        id: 'fresh',
        pageBg: 'bg-emerald-50/30',
        mobileNavBg: 'bg-white',
        text: 'text-emerald-950',
        textMuted: 'text-emerald-700',
        header: 'bg-white border-b border-emerald-100 shadow-sm relative z-50',
        headerWrapper: 'max-w-[1440px] mx-auto px-4 sm:px-6 lg:px-8 h-20 flex items-center justify-between',
        headerLogo: 'text-emerald-700 font-bold',
        heroShape: 'rounded-none', // Removed bottom right leaf shape for full width
        heroOverlay: 'bg-emerald-900/5',
        gridCols: 'grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-4 sm:gap-6', // Dense but rounded
        cardStyle: 'bg-white border border-emerald-50 rounded-2xl shadow-sm hover:shadow-md hover:border-emerald-200 transition-all',
        cardImageStyle: 'aspect-[4/5] rounded-t-2xl bg-emerald-50',
        badgeStyle: 'bg-emerald-500 text-white rounded-lg px-2.5 py-0.5 text-xs font-semibold',
        priceStyle: 'text-emerald-700 font-bold text-lg',
        priceCompareStyle: 'text-emerald-700/60 line-through text-sm',
        buttonStyle: 'w-full py-2 bg-emerald-100 text-emerald-700 hover:bg-emerald-500 hover:text-white font-semibold rounded-xl transition-colors',
        categoryTab: 'bg-white text-emerald-800 rounded-xl hover:bg-emerald-50 hover:text-emerald-700 border border-emerald-50',
        categoryTabActive: 'bg-emerald-500 text-white rounded-xl font-medium shadow-sm shadow-emerald-200',
        searchStyle: 'bg-emerald-50/50 border border-emerald-100 text-emerald-950 rounded-xl focus:border-emerald-400 focus:ring-2 focus:ring-emerald-100 placeholder-emerald-700/50',
        fontFamily: "'Quicksand', sans-serif",
        cartButton: 'bg-emerald-50 text-emerald-700 rounded-xl hover:bg-emerald-100',
        cartBadge: 'bg-emerald-500 text-white',
    },
    pulse: {
        id: 'pulse',
        pageBg: 'bg-zinc-900',
        text: 'text-zinc-100',
        textMuted: 'text-zinc-400',
        header: 'bg-zinc-900 border-b border-zinc-800',
        headerWrapper: 'max-w-[1440px] mx-auto px-4 sm:px-6 lg:px-8 h-20 flex items-center justify-between',
        headerLogo: 'text-yellow-400 font-black italic tracking-tighter uppercase',
        menuButton: 'text-yellow-400 hover:text-yellow-300 hover:bg-zinc-800', // Added high-contrast menu button
        heroShape: 'clip-path-[polygon(0_0,100%_0,100%_90%,50%_100%,0_90%)]', // Chevron bottom
        heroOverlay: 'bg-black/10',
        gridCols: 'grid-cols-1 sm:grid-cols-2 gap-6 lg:gap-8',
        cardStyle: 'bg-zinc-800 border-l-4 border-transparent hover:border-yellow-400 rounded overflow-hidden shadow-lg transition-all',
        cardImageStyle: 'aspect-square bg-white rounded-t', // Increased size and white bg to fix mix-blend blank images
        badgeStyle: 'bg-yellow-400 text-zinc-950 font-black uppercase italic px-2 py-1',
        priceStyle: 'text-yellow-400 font-black text-2xl italic',
        priceCompareStyle: 'text-zinc-500 line-through font-bold text-sm',
        buttonStyle: 'w-full py-3 bg-zinc-900 text-yellow-400 border border-zinc-700 hover:bg-yellow-400 hover:text-zinc-950 font-black uppercase italic tracking-wider transition-colors skew-x-[-10deg]', // Skewed button
        categoryTab: 'bg-zinc-800 text-zinc-400 font-bold uppercase italic hover:text-yellow-400 hover:bg-zinc-800 skew-x-[-10deg]',
        categoryTabActive: 'bg-yellow-400 text-zinc-950 font-black uppercase italic shadow-[0_0_15px_rgba(250,204,21,0.3)] skew-x-[-10deg]',
        searchStyle: 'bg-zinc-800 border-none text-zinc-100 rounded focus:ring-2 focus:ring-yellow-400 placeholder-zinc-500 font-bold italic',
        fontFamily: "'Outfit', sans-serif",
        cartButton: 'bg-zinc-800 text-yellow-400 border border-zinc-700 hover:border-yellow-400 rounded skew-x-[-10deg]',
        cartBadge: 'bg-yellow-400 text-zinc-950',
    },
    professional: {
        id: 'professional',
        pageBg: 'bg-slate-50',
        text: 'text-slate-800',
        textMuted: 'text-slate-500',
        header: 'bg-white border-b border-slate-200 shadow-sm',
        headerWrapper: 'max-w-[1440px] mx-auto px-4 sm:px-6 lg:px-8 h-20 flex items-center justify-between',
        headerLogo: 'text-blue-700 font-bold tracking-tight',
        heroShape: 'rounded-none',
        heroOverlay: 'bg-blue-900/10',
        gridCols: 'grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6',
        cardStyle: 'bg-white border border-slate-200 rounded-md hover:shadow-lg transition-shadow overflow-hidden',
        cardImageStyle: 'aspect-[4/5] bg-slate-100 border-b border-slate-100',
        badgeStyle: 'bg-blue-600 text-white rounded px-2 py-0.5 text-xs font-medium',
        priceStyle: 'text-slate-900 font-semibold text-lg',
        priceCompareStyle: 'text-slate-500 line-through text-sm',
        buttonStyle: 'w-full py-2 bg-blue-600 text-white hover:bg-blue-700 font-medium rounded transition-colors shadow-sm',
        categoryTab: 'bg-white text-slate-600 border border-slate-200 rounded hover:bg-slate-50 hover:text-blue-600',
        categoryTabActive: 'bg-blue-50 text-blue-700 border border-blue-200 rounded font-medium',
        searchStyle: 'bg-white border border-slate-300 text-slate-800 rounded focus:border-blue-500 focus:ring-1 focus:ring-blue-500 placeholder-slate-400',
        fontFamily: "system-ui, -apple-system, sans-serif",
        cartButton: 'bg-white text-slate-600 border border-slate-200 rounded hover:text-blue-600 hover:border-blue-200',
        cartBadge: 'bg-blue-600 text-white rounded',
    },
    amber: {
        id: 'amber',
        pageBg: 'bg-[#FAF7F2]',
        mobileNavBg: 'bg-[#DFD5C3]',
        text: 'text-[#261A14]',
        textMuted: 'text-[#6E584B]',
        header: 'bg-[#DFD5C3] border-b border-[#CDC1AE] text-[#261A14] shadow-sm sticky top-0 z-50',
        headerWrapper: 'max-w-[1440px] mx-auto px-4 sm:px-6 lg:px-8 h-20 sm:h-24 flex items-center justify-between relative',
        headerLogo: 'text-[#261A14] tracking-tight font-bold',
        heroShape: 'rounded-none overflow-hidden border-b border-[#CDC1AE]',
        heroOverlay: 'bg-gradient-to-t from-[#261A14]/75 via-[#261A14]/20 to-transparent',
        gridCols: 'grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-4 sm:gap-6',
        cardStyle: 'bg-white border border-[#EAE2D5] rounded-2xl shadow-[0_4px_20px_-4px_rgba(38,26,20,0.05)] hover:shadow-[0_14px_30px_-6px_rgba(38,26,20,0.12)] hover:border-[#CDC1AE] transition-all duration-300 overflow-hidden group flex flex-col h-full',
        cardImageStyle: 'aspect-square bg-[#FDFBF7] p-3 sm:p-4 flex items-center justify-center relative overflow-hidden rounded-t-2xl border-b border-[#F5EFEB]',
        badgeStyle: 'bg-[#261A14] text-[#DFD5C3] rounded-full px-2.5 sm:px-3 py-1 text-[10px] font-bold uppercase tracking-wider shadow-sm',
        priceStyle: 'text-[#261A14] font-bold text-base sm:text-xl tracking-tight',
        priceCompareStyle: 'text-[#8E796C] line-through text-xs sm:text-sm font-normal',
        buttonStyle: 'w-full py-2.5 sm:py-3 bg-[#261A14] text-[#FAF7F2] hover:bg-[#3D2B22] active:bg-[#1A120E] rounded-xl font-medium tracking-wider text-[11px] sm:text-xs uppercase transition-all duration-200 shadow-sm active:scale-[0.98] flex items-center justify-center gap-1.5',
        categoryTab: 'bg-[#F2ECE1] text-[#6E584B] border border-[#DFD5C3] rounded-full hover:bg-[#DFD5C3] hover:text-[#261A14] transition-colors',
        categoryTabActive: 'bg-[#261A14] text-[#FAF7F2] border border-[#261A14] rounded-full font-semibold shadow-sm',
        searchStyle: 'bg-[#F0E8DC] border border-[#CDC1AE] text-[#261A14] rounded-full focus:border-[#261A14] focus:ring-1 focus:ring-[#261A14] placeholder-[#8E796C] text-sm transition-colors',
        fontFamily: "'Outfit', sans-serif",
        cartButton: 'bg-[#ECE3D5] text-[#261A14] rounded-full hover:bg-[#D5CABB] border border-[#CDC1AE] transition-colors',
        cartBadge: 'bg-[#261A14] text-[#DFD5C3] rounded-full font-bold',
    }
};

export const DEFAULT_THEME = THEMES.vogue;

export function getThemeConfig(themeId) {
    return THEMES[themeId] || DEFAULT_THEME;
}
