export const THEMES = {
    vogue: {
        id: 'vogue',
        pageBg: 'bg-white',
        text: 'text-black',
        textMuted: 'text-gray-500',
        header: 'bg-white border-b border-gray-200',
        headerWrapper: 'max-w-[1440px] mx-auto px-4 sm:px-6 lg:px-8 h-24 grid grid-cols-3 items-center',
        logoWrapper: 'justify-self-center col-start-2 flex flex-row items-center',
        searchWrapper: 'hidden md:flex justify-self-start col-start-1 w-full max-w-xs',
        cartWrapper: 'justify-self-end col-start-3',
        headerLogo: 'hidden',
        heroShape: 'rounded-none',
        heroOverlay: 'bg-black/5',
        gridCols: 'grid-cols-1 sm:grid-cols-2 lg:grid-cols-2 gap-x-12 gap-y-16', // 2 columns for gallery look
        cardStyle: 'bg-white border border-gray-100 rounded-2xl shadow-sm hover:shadow-lg hover:border-gray-200 transition-all duration-300 overflow-hidden',
        cardImageStyle: 'aspect-square rounded-t-2xl bg-gray-50 border-b border-gray-100',
        badgeStyle: 'bg-black text-white rounded-full px-2.5 py-1 text-[10px] font-semibold uppercase tracking-wider',
        priceStyle: 'text-black font-medium text-lg',
        priceCompareStyle: 'text-gray-400 line-through text-sm',
        buttonStyle: 'w-full py-3 bg-white text-black border border-black hover:bg-black hover:text-white uppercase tracking-widest text-xs transition-colors rounded-[15px]',
        categoryTab: 'bg-transparent text-gray-500 border-b-2 border-transparent hover:text-black',
        categoryTabActive: 'bg-transparent text-black border-b-2 border-black font-semibold',
        searchStyle: 'bg-gray-50 border-none rounded-none focus:ring-1 focus:ring-black',
        fontFamily: "'Outfit', sans-serif",
        cartButton: 'bg-black text-white rounded-none hover:bg-gray-900',
        cartBadge: 'bg-white text-black',
    },
    cyber: {
        id: 'cyber',
        pageBg: 'bg-slate-950',
        text: 'text-cyan-50',
        textMuted: 'text-cyan-600/60',
        header: 'absolute top-0 w-full z-50 bg-slate-950/40 backdrop-blur-md border-b border-cyan-900/30', // Floating/overlay
        headerWrapper: 'max-w-[1440px] mx-auto px-4 sm:px-6 lg:px-8 h-20 flex items-center justify-between',
        headerLogo: 'text-cyan-400 font-mono tracking-tighter',
        heroShape: 'clip-path-[polygon(0_0,100%_0,100%_85%,0_100%)]', // Slanted bottom
        heroOverlay: 'bg-gradient-to-t from-slate-950/60 to-transparent',
        gridCols: 'grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6', // Dense
        cardStyle: 'bg-slate-900/50 border border-cyan-900/30 rounded-lg hover:border-cyan-500/50 hover:shadow-[0_0_15px_rgba(6,182,212,0.2)] transition-all',
        cardImageStyle: 'aspect-[4/5] rounded-t-lg bg-slate-900 border-b border-cyan-900/30',
        badgeStyle: 'bg-cyan-500 text-slate-950 rounded shadow-[0_0_10px_rgba(6,182,212,0.5)]',
        priceStyle: 'text-cyan-400 font-mono font-bold text-lg',
        priceCompareStyle: 'text-slate-600 line-through font-mono text-sm',
        buttonStyle: 'w-full py-2.5 bg-cyan-950/50 text-cyan-400 border border-cyan-800 hover:bg-cyan-500 hover:text-slate-950 hover:shadow-[0_0_15px_rgba(6,182,212,0.5)] font-mono text-sm transition-all rounded',
        categoryTab: 'bg-slate-900/50 text-cyan-700 border border-cyan-900/30 rounded font-mono hover:text-cyan-400 hover:border-cyan-700',
        categoryTabActive: 'bg-cyan-950 text-cyan-400 border border-cyan-500 rounded font-mono shadow-[0_0_10px_rgba(6,182,212,0.2)]',
        searchStyle: 'bg-slate-900/50 border border-cyan-900/30 text-cyan-50 rounded font-mono focus:border-cyan-500 focus:ring-1 focus:ring-cyan-500 placeholder-cyan-800',
        fontFamily: "'Space Grotesk', monospace, sans-serif",
        cartButton: 'bg-cyan-950/50 text-cyan-400 border border-cyan-800 rounded hover:bg-cyan-900 hover:text-cyan-300',
        cartBadge: 'bg-cyan-500 text-slate-950',
    },
    glow: {
        id: 'glow',
        pageBg: 'bg-rose-50/50',
        text: 'text-rose-950',
        textMuted: 'text-rose-400',
        header: 'bg-white/70 backdrop-blur-xl border-b border-rose-100',
        headerWrapper: 'max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 h-20 flex items-center justify-between', // Centered max-w
        headerLogo: 'text-rose-600',
        heroShape: 'rounded-b-[4rem] sm:rounded-b-[6rem]', // Huge bottom curve
        heroOverlay: 'bg-rose-900/5',
        gridCols: 'grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8',
        cardStyle: 'bg-white/60 backdrop-blur-lg border border-white rounded-3xl shadow-sm hover:shadow-xl hover:shadow-rose-100/50 transition-all duration-500',
        cardImageStyle: 'aspect-[3/4] rounded-t-3xl bg-rose-50/50 p-2',
        badgeStyle: 'bg-gradient-to-r from-rose-400 to-pink-400 text-white rounded-full px-3 py-1 text-[10px]',
        priceStyle: 'text-rose-900 font-semibold text-lg',
        priceCompareStyle: 'text-rose-300 line-through text-sm',
        buttonStyle: 'w-full py-3 bg-gradient-to-r from-rose-400 to-pink-500 text-white hover:from-rose-500 hover:to-pink-600 rounded-2xl shadow-md shadow-rose-200 transition-all font-medium',
        categoryTab: 'bg-white/60 text-rose-400 rounded-full hover:bg-rose-100/50 hover:text-rose-600',
        categoryTabActive: 'bg-rose-100 text-rose-700 rounded-full font-medium shadow-sm',
        searchStyle: 'bg-white/60 border border-white text-rose-900 rounded-full focus:ring-2 focus:ring-rose-200 placeholder-rose-300 shadow-inner',
        fontFamily: "'Outfit', sans-serif",
        cartButton: 'bg-rose-100 text-rose-600 rounded-full hover:bg-rose-200',
        cartBadge: 'bg-gradient-to-r from-rose-400 to-pink-500 text-white',
    },
    luxe: {
        id: 'luxe',
        pageBg: 'bg-zinc-950',
        text: 'text-zinc-100',
        textMuted: 'text-zinc-500',
        header: 'bg-zinc-950 border-b border-yellow-900/30',
        headerWrapper: 'max-w-[1440px] mx-auto px-4 sm:px-6 lg:px-8 h-24 grid grid-cols-3 items-center', // True centered logo using Grid
        logoWrapper: 'justify-self-center col-start-2',
        searchWrapper: 'hidden md:flex justify-self-start col-start-1 w-full max-w-sm',
        cartWrapper: 'justify-self-end col-start-3',
        headerLogo: 'text-yellow-500 tracking-widest uppercase text-2xl',
        heroShape: 'rounded-none',
        heroOverlay: 'bg-black/10',
        gridCols: 'grid-cols-1 sm:grid-cols-2 gap-px bg-zinc-800/50', // Border lines via gap
        cardStyle: 'bg-zinc-950 rounded-none group-hover:bg-zinc-900 transition-colors',
        cardImageStyle: 'aspect-[2/3] bg-zinc-900 rounded-none mix-blend-luminosity hover:mix-blend-normal transition-all duration-700',
        badgeStyle: 'bg-yellow-600 text-zinc-950 rounded-none text-[10px] uppercase tracking-widest',
        priceStyle: 'text-yellow-500 font-light tracking-wide text-lg',
        priceCompareStyle: 'text-zinc-600 line-through text-sm',
        buttonStyle: 'w-full py-3 bg-transparent text-yellow-500 border border-yellow-900/50 hover:border-yellow-500 hover:bg-yellow-500 hover:text-zinc-950 uppercase tracking-widest text-xs transition-all rounded-none',
        categoryTab: 'bg-transparent text-zinc-500 rounded-none uppercase tracking-widest text-xs hover:text-yellow-600',
        categoryTabActive: 'bg-transparent text-yellow-500 rounded-none uppercase tracking-widest text-xs border-b border-yellow-500',
        searchStyle: 'bg-zinc-900 border border-zinc-800 text-zinc-100 rounded-none focus:border-yellow-700 focus:ring-0 placeholder-zinc-600 uppercase text-xs tracking-wider',
        fontFamily: "'Cinzel', serif",
        cartButton: 'bg-zinc-900 text-yellow-500 rounded-none border border-zinc-800 hover:border-yellow-900/50',
        cartBadge: 'bg-yellow-600 text-zinc-950 rounded-none',
    },
    crave: {
        id: 'crave',
        pageBg: 'bg-orange-50',
        text: 'text-amber-950',
        textMuted: 'text-orange-700/60',
        header: 'bg-orange-50/90 backdrop-blur-sm border-b border-orange-200/50',
        headerWrapper: 'max-w-[1440px] mx-auto px-4 sm:px-6 lg:px-8 h-20 flex items-center justify-between',
        headerLogo: 'text-red-600 font-black',
        heroShape: 'rounded-b-3xl mx-2 sm:mx-4 mt-2', // Floating boxed hero
        heroOverlay: 'bg-gradient-to-t from-orange-900/10 to-transparent',
        gridCols: 'grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6',
        cardStyle: 'bg-white border-2 border-transparent hover:border-orange-200 rounded-3xl shadow-sm hover:shadow-xl hover:shadow-orange-200/50 transition-all duration-300 overflow-hidden',
        cardImageStyle: 'aspect-square rounded-t-3xl bg-orange-100',
        badgeStyle: 'bg-red-500 text-white rounded-full font-bold px-3 py-1',
        priceStyle: 'text-red-600 font-black text-xl',
        priceCompareStyle: 'text-orange-300 line-through font-medium text-sm',
        buttonStyle: 'w-full py-3.5 bg-red-500 text-white hover:bg-red-600 rounded-2xl shadow-[0_4px_0_rgb(185,28,28)] active:shadow-[0_0px_0_rgb(185,28,28)] active:translate-y-1 font-bold text-base transition-all',
        categoryTab: 'bg-white text-orange-600 rounded-full font-bold hover:bg-orange-100 hover:text-red-600 shadow-sm border border-orange-100',
        categoryTabActive: 'bg-red-500 text-white rounded-full font-bold shadow-md shadow-red-500/30',
        searchStyle: 'bg-white border border-orange-200 text-amber-950 rounded-2xl focus:border-red-400 focus:ring-4 focus:ring-red-100 placeholder-orange-300 font-medium',
        fontFamily: "'Nunito', sans-serif",
        cartButton: 'bg-white text-red-500 rounded-2xl border border-orange-200 hover:bg-red-50 hover:border-red-200 shadow-sm',
        cartBadge: 'bg-red-500 text-white',
    },
    nordic: {
        id: 'nordic',
        pageBg: 'bg-[#F9F6F0]',
        text: 'text-[#4A4A4A]',
        textMuted: 'text-[#8C8273]',
        header: 'bg-[#F9F6F0] border-b border-[#E5D9C5]',
        headerWrapper: 'max-w-[1440px] mx-auto px-4 sm:px-6 lg:px-8 h-20 flex items-center justify-between',
        headerLogo: 'text-[#4A4A4A] tracking-tight',
        heroShape: 'rounded-none border-b-8 border-[#E5D9C5]',
        heroOverlay: 'bg-[#8C8273]/5',
        gridCols: 'grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-10',
        cardStyle: 'bg-[#F9F6F0] border-none rounded-none',
        cardImageStyle: 'aspect-[4/5] bg-[#E5D9C5] rounded-none',
        badgeStyle: 'bg-[#8C8273] text-[#F9F6F0] rounded-none px-2 py-1 text-xs',
        priceStyle: 'text-[#4A4A4A] text-lg',
        priceCompareStyle: 'text-[#bdae97] line-through text-sm',
        buttonStyle: 'w-full py-3 bg-[#8C8273] text-[#F9F6F0] hover:bg-[#6e6559] transition-colors rounded-none text-sm tracking-wide',
        categoryTab: 'bg-transparent text-[#8C8273] rounded-none hover:text-[#4A4A4A]',
        categoryTabActive: 'bg-transparent text-[#4A4A4A] rounded-none border-b-2 border-[#4A4A4A]',
        searchStyle: 'bg-[#F9F6F0] border border-[#E5D9C5] text-[#4A4A4A] rounded-none focus:border-[#8C8273] focus:ring-0 placeholder-[#bdae97]',
        fontFamily: "'Inter', sans-serif",
        cartButton: 'bg-[#E5D9C5] text-[#4A4A4A] rounded-none hover:bg-[#d6c7af]',
        cartBadge: 'bg-[#8C8273] text-[#F9F6F0]',
    },
    fresh: {
        id: 'fresh',
        pageBg: 'bg-emerald-50/30',
        text: 'text-slate-800',
        textMuted: 'text-slate-500',
        header: 'bg-white border-b border-emerald-100 shadow-sm relative z-50',
        headerWrapper: 'max-w-[1440px] mx-auto px-4 sm:px-6 lg:px-8 h-20 flex items-center justify-between',
        headerLogo: 'text-emerald-700 font-bold',
        heroShape: 'rounded-br-[5rem]', // Unique bottom right leaf shape
        heroOverlay: 'bg-emerald-900/5',
        gridCols: 'grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-4 sm:gap-6', // Dense but rounded
        cardStyle: 'bg-white border border-emerald-50 rounded-2xl shadow-sm hover:shadow-md hover:border-emerald-200 transition-all',
        cardImageStyle: 'aspect-[4/5] rounded-t-2xl bg-emerald-50 p-4',
        badgeStyle: 'bg-emerald-500 text-white rounded-lg px-2.5 py-0.5 text-xs font-semibold',
        priceStyle: 'text-emerald-700 font-bold text-lg',
        priceCompareStyle: 'text-slate-400 line-through text-sm',
        buttonStyle: 'w-full py-2 bg-emerald-100 text-emerald-700 hover:bg-emerald-500 hover:text-white font-semibold rounded-xl transition-colors',
        categoryTab: 'bg-white text-slate-600 rounded-xl hover:bg-emerald-50 hover:text-emerald-700 border border-emerald-50',
        categoryTabActive: 'bg-emerald-500 text-white rounded-xl font-medium shadow-sm shadow-emerald-200',
        searchStyle: 'bg-emerald-50/50 border border-emerald-100 text-slate-800 rounded-xl focus:border-emerald-400 focus:ring-2 focus:ring-emerald-100 placeholder-slate-400',
        fontFamily: "'Quicksand', sans-serif",
        cartButton: 'bg-emerald-50 text-emerald-700 rounded-xl hover:bg-emerald-100',
        cartBadge: 'bg-emerald-500 text-white',
    },
    pulse: {
        id: 'pulse',
        pageBg: 'bg-zinc-900',
        text: 'text-zinc-100',
        textMuted: 'text-zinc-400',
        header: 'bg-zinc-900 border-b border-zinc-800',
        headerWrapper: 'max-w-[1440px] mx-auto px-4 sm:px-6 lg:px-8 h-20 flex items-center justify-between',
        headerLogo: 'text-yellow-400 font-black italic tracking-tighter uppercase',
        heroShape: 'clip-path-[polygon(0_0,100%_0,100%_90%,50%_100%,0_90%)]', // Chevron bottom
        heroOverlay: 'bg-black/10',
        gridCols: 'grid-cols-1 sm:grid-cols-2 gap-6 lg:gap-8',
        cardStyle: 'bg-zinc-800 border-l-4 border-transparent hover:border-yellow-400 rounded overflow-hidden shadow-lg transition-all',
        cardImageStyle: 'aspect-[4/3] bg-zinc-950', // Wider landscape images
        badgeStyle: 'bg-yellow-400 text-zinc-950 font-black uppercase italic px-2 py-1',
        priceStyle: 'text-yellow-400 font-black text-2xl italic',
        priceCompareStyle: 'text-zinc-500 line-through font-bold text-sm',
        buttonStyle: 'w-full py-3 bg-zinc-900 text-yellow-400 border border-zinc-700 hover:bg-yellow-400 hover:text-zinc-950 font-black uppercase italic tracking-wider transition-colors skew-x-[-10deg]', // Skewed button
        categoryTab: 'bg-zinc-800 text-zinc-400 font-bold uppercase italic hover:text-yellow-400 hover:bg-zinc-800 skew-x-[-10deg]',
        categoryTabActive: 'bg-yellow-400 text-zinc-950 font-black uppercase italic shadow-[0_0_15px_rgba(250,204,21,0.3)] skew-x-[-10deg]',
        searchStyle: 'bg-zinc-800 border-none text-zinc-100 rounded focus:ring-2 focus:ring-yellow-400 placeholder-zinc-500 font-bold italic',
        fontFamily: "'Teko', sans-serif",
        cartButton: 'bg-zinc-800 text-yellow-400 border border-zinc-700 hover:border-yellow-400 rounded skew-x-[-10deg]',
        cartBadge: 'bg-yellow-400 text-zinc-950',
    },
    professional: {
        id: 'professional',
        pageBg: 'bg-slate-50',
        text: 'text-slate-800',
        textMuted: 'text-slate-500',
        header: 'bg-white border-b border-slate-200 shadow-sm',
        headerWrapper: 'max-w-[1440px] mx-auto px-4 sm:px-6 lg:px-8 h-20 flex items-center justify-between',
        headerLogo: 'text-blue-700 font-bold tracking-tight',
        heroShape: 'rounded-none',
        heroOverlay: 'bg-blue-900/10',
        gridCols: 'grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6',
        cardStyle: 'bg-white border border-slate-200 rounded-md hover:shadow-lg transition-shadow overflow-hidden',
        cardImageStyle: 'aspect-[4/5] bg-slate-100 border-b border-slate-100',
        badgeStyle: 'bg-blue-600 text-white rounded px-2 py-0.5 text-xs font-medium',
        priceStyle: 'text-slate-900 font-semibold text-lg',
        priceCompareStyle: 'text-slate-400 line-through text-sm',
        buttonStyle: 'w-full py-2 bg-blue-600 text-white hover:bg-blue-700 font-medium rounded transition-colors shadow-sm',
        categoryTab: 'bg-white text-slate-600 border border-slate-200 rounded hover:bg-slate-50 hover:text-blue-600',
        categoryTabActive: 'bg-blue-50 text-blue-700 border border-blue-200 rounded font-medium',
        searchStyle: 'bg-white border border-slate-300 text-slate-800 rounded focus:border-blue-500 focus:ring-1 focus:ring-blue-500 placeholder-slate-400',
        fontFamily: "system-ui, -apple-system, sans-serif",
        cartButton: 'bg-white text-slate-600 border border-slate-200 rounded hover:text-blue-600 hover:border-blue-200',
        cartBadge: 'bg-blue-600 text-white rounded',
    }
};

export const DEFAULT_THEME = THEMES.vogue;

export function getThemeConfig(themeId) {
    return THEMES[themeId] || DEFAULT_THEME;
}
